### ISSUE TITLE
Bundling issue

### ISSUE THREAD

**Issue by tborychowski** [b1lly/gulp-rollup-stream#1]
Hi,

First of all - thanks for this plugin - this is the only one (rollup & gulp) that actually worked.
However, in the recent update of rollup (and/or gulp) I started to get some weird console logs for rollup plugins, e.g.:
```
The "buildStart" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "resolveId" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
The "load" hook used by the output plugin node-resolve is a build time hook and will not be run for that plugin. Either this plugin cannot be used as an output plugin, or it should have an option to configure it as an output plugin.
```

After a lot of investigation (with devs of these plugins) I was able to pinpoint the issue to the options passed to rollup.
From [their docs](https://rollupjs.org/guide/en/#javascript-api) it seems that `inputOptions` and `outputOptions`, in the javascript api, should be separated.
If we pass a regular rollup config to both (as your plugin does at the moment) - we will get these messages logs, because some rollup plugins work for input, whereas others - for output.
 
I was able to fix my use case, by modifying your code like so:
```js
const stream = require('stream');
const rollup = require('rollup');

module.exports = function (opts = {}) {
	const readable = new stream.Readable();
	const {input, plugins, output} = opts;
	const io = {input, plugins};
	const oo = { output };
	readable._read = function () { };
	rollup
		.rollup(io)
		.then(bundle => bundle.generate(oo))
		.then(out => {
			if (!out.code) out = out.output[0];
			readable.push(out.code);
			if (opts.sourcemap || opts.sourceMap || opts.output.sourcemap || opts.output.sourceMap) {
				readable.push('\n//# sourceMappingURL=');
				readable.push(out.map.toUrl());
			}
			readable.push(null);
		})
		.catch(error => setTimeout(() => readable.emit('error', error)));
	return readable;
};
```
But it will probably not work for all config options (and all rollup plugins).
I don't know rollup well enough to fix that in a better way :-)
Hopefully you can think of something.

**Comment by b1lly** [comment]
Hi @tborychowski, sorry for taking a so long to get back to you. I actually fixed this in https://github.com/b1lly/gulp-rollup-lightweight/commit/b578eaa702adda56d587d314adcf4056da684754

I separated the two objects to update the interface. It's backwards compatable, so it should work with the old interface of a single configuration object, and the new interface with the 'input and output' configuration objects.
